% Build geometry
[chnkr, target, charge1, charge2] = get_torus_geometry();

origin = [0;0];

% For your torus builder, the natural centerline ring is at ctr = [3,0]
r0 = 3.0;
z0 = 0.0;

[scale, c] = normalize_ring_loop_ampere(chnkr, origin, r0, z0);

fprintf('Raw circulation c = %.15e\n', c);
fprintf('Use scale = %.15e so normalized circulation is 1\n', scale);

% Later, when you inject the loop term into BC:
alpha_desired = 0.7;                 % the circulation you want
alpha_eff = alpha_desired * scale;   % multiply your loop contribution by alpha_eff






function [chnkobj,target,charge1,charge2] = get_torus_geometry()
    pref = [];
    pref.k = 16; % points per chunk
    %pref.nchmax = 2;

    cparams = [];
    %cparams.eps = 1.0e-10;
    %cparams.nover = 1;
    cparams.ifclosed = true;
    cparams.ta = 0;
    cparams.tb = 2*pi;
    cparams.maxchunklen = 2;
    %cparams.nchmin = 8;

    ctr = [3 0];
    narms = 0;
    amp = 0.25;

    chnkobj = chunkerfunc(@(t) starfish(t, narms, amp, ctr), cparams, pref); 
    chnkobj = sort(chnkobj);

    target = [3;0.0;-0.7];
    charge1 = [1.0;0.0;3.0];
    charge2 = [1.0;0.0;-3.0];
end


function [scale, c] = normalize_ring_loop_ampere(chnkr, origin, r0, z0)
% One-time normalization: c = ∮_A (1/mu curl A[L]) · ds for ring loop at (r0,z0)
% A-cycle here is the meridian (generating curve at fixed phi).

    % ---- Flatten chunkie geometry to 2 x Nt arrays ----
    targ_rz = chnkr.r;
    if ndims(targ_rz) == 3
        targ_rz = reshape(targ_rz, 2, []);     % 2 x (k*nch)
    end

    wts = chnkr.wts(:);
    Nt  = numel(wts);

    if size(targ_rz,2) ~= Nt
        error('Expected targ_rz to have Nt=%d points, but got %d.', Nt, size(targ_rz,2));
    end

    % ---- Compute H_loop = (1/mu) curl(A) using your modal helper (mu=1) ----
    [H_r, H_z] = curlA_ring_modal(targ_rz, origin, r0, z0, 1);
    H_r = H_r(:);  H_z = H_z(:);

    % ---- Tangent on generating curve ----
    if isfield(chnkr,'d') && ~isempty(chnkr.d)
        d = chnkr.d;
        if ndims(d) == 3
            d = reshape(d, 2, []);
        end
        drdt = d(1,:).';
        dzdt = d(2,:).';
    else
        % fallback: finite difference on flattened nodes (periodic)
        r = targ_rz(1,:).';
        z = targ_rz(2,:).';
        drdt = 0.5*(circshift(r,-1) - circshift(r,1));
        dzdt = 0.5*(circshift(z,-1) - circshift(z,1));
    end

    spd = sqrt(drdt.^2 + dzdt.^2);
    t_r = drdt ./ spd;
    t_z = dzdt ./ spd;

    % ---- Final size sanity ----
    if any([numel(H_r), numel(H_z), numel(t_r), numel(t_z)] ~= Nt)
        error('Size mismatch after flattening: Nt=%d | H_r=%d H_z=%d t_r=%d t_z=%d', ...
            Nt, numel(H_r), numel(H_z), numel(t_r), numel(t_z));
    end

    % ---- Circulation integral c = ∮ H · t_hat ds ----
    HdotT = H_r .* t_r + H_z .* t_z;    % Nt x 1
    c = sum(HdotT .* wts);              % scalar

    scale = 1 / c;
end



function [curlA_r, curlA_z, Aphi, dAphidr, dAphidz] = curlA_ring_modal(targ_rz, origin, r0, z0, mu)
% curlA_ring_modal
% Compute curl(A[L]) for a unit-current circular loop L located at (r0,z0)
% using chnk.axissymlap2d.green_modal (your modal Laplace Green evaluator).
%
% INPUTS:
%   targ_rz : 2 x Nt array of target points in (r,z) coordinates (same convention as kern_modal)
%   origin  : [origin_r; origin_z] used by your code (note: your green_modal only uses origin(1) to shift r)
%   r0,z0   : meridian location of the loop (generating point of the ring)
%   mu      : permeability (set mu=1 if you want)
%
% OUTPUTS (axisymmetric cylindrical components):
%   curlA_r, curlA_z : Nt x 1 arrays giving (∇×A)_r and (∇×A)_z
%   Aphi             : Nt x 1 azimuthal component A_phi
%   dAphidr, dAphidz : Nt x 1 derivatives of A_phi wrt target r and z

    if nargin < 5 || isempty(mu)
        mu = 1;
    end

    % One source: the ring is generated by the point (r0,z0)
    src_rz = [r0; z0];

    % IMPORTANT: your green_modal expects MATLAB-indexed "m"
    % where mode n corresponds to m = n+1. So n=1 => m=2.
    m = 2;

    % Evaluate mode-1 scalar modal Green and its target derivatives
    [val, grad] = chnk.axissymlap2d.green_modal(src_rz, targ_rz, origin, m, false);

    % val is Nt x 1 (since ns=1). grad is Nt x 1 x 4 with:
    % grad(:,:,1)=d_r, grad(:,:,2)=d_{r'}, grad(:,:,3)=d_z, grad(:,:,4)=d_{z'}
    val  = val(:,1);
    dr   = grad(:,1,1);
    dz   = grad(:,1,3);

    % With your scaling: A_phi = mu * Re(val_mode1)
    Aphi    = mu * real(val);
    dAphidr = mu * real(dr);
    dAphidz = mu * real(dz);

    % Need the *physical* cylindrical radius r used in the curl formula
    r_phys = targ_rz(1,:).' + origin(1);

    % Safety if any targets hit the axis (usually not for a torus)
    r_phys = max(r_phys, 1e-15);

    % Curl in cylindrical coords for axisymmetric A = A_phi e_phi
    curlA_r = -dAphidz;
    curlA_z = (Aphi ./ r_phys) + dAphidr;
end